import './globals.css';
import Header from './(components)/Header';
import { AuthProvider } from './(utils)/AuthContext';

export const metadata = {
  title: 'Liga de Tenis NJS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className='p-2'>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
};
