import './globals.css';
import Header from '../components/Header';
import { AuthProvider } from '../utils/AuthContext';
import Providers from './Providers';

export const metadata = {
  title: 'Liga de Tenis NJS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='p-2'>
        <Providers>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
};
